
### add task new
POST http://localhost:3200/task
Content-Type: application/json
{
    "title": "Party #1",
    "date": "2023-06-05",
    "description":"It is my birthday",
    "priority": "normal",
    "status":"doing"

}

### get task by Id
GET http://localhost:3200/task/28

Content-Type: application/json
### save task data
PUT http://localhost:3200/task/28
Content-Type: application/json
{
    "title": "My Party",
    "date": "2022-06-05",
    "description":"Yeah Supper Show"
}
### save task status
PUT http://localhost:3200/task/25
Content-Type: application/json
{
    "status": "done"
}
### fetch tasks list
GET http://localhost:3200/tasks
Content-Type: application/json