
### add task new
POST http://localhost:3200/task
Content-Type: application/json

{
    "title": "Festa 16",
    "date": "2023-10-27",
    "description":"Glamorosa",
    "priority": "normal",
    "status":"todo",
    "reason":"I am so excited!"
}

### get task by Id
GET http://localhost:3200/task/11

Content-Type: application/json
### save task status
PUT http://localhost:3200/task/23
Content-Type: application/json
{
    "status": "done"
}
### fetch tasks list
GET http://localhost:3200/tasks
Content-Type: application/json