version: "3"
services: 
  db:
    container_name: todo-api
    hostname: todo-api
    image: mysql
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "Todo"
      MYSQL_ROOT_PASSWORD: "admin"
    volumes: 
      - todoDB:/var/lib/mysql
volumes:
  todoDB: 